apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm64-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arm64-app
  template:
    metadata:
      labels:
        app: arm64-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            cpu: 500m
            memory: 512Mi